In [1]:
# import sys
# from pathlib import Path

# # go one level up from notebooks/ to project root
# project_root = Path().resolve().parent

# sys.path.append(str(project_root))

In [2]:
import os
os.chdir("..")  # move from notebooks/ to project root

In [3]:
import pandas as pd
import numpy as np

In [4]:
from src.models.dataset import EvaluationDataset
from src.evaluation.multi_model_runner import run_multi_model_evaluation
from src.evaluation.judge import judge_correctness
from src.core.versioning import compute_dataset_version

In [5]:
dataset = EvaluationDataset.from_csv(path="data/dataset.csv")

models = ["mistral", "gemma2"]

In [6]:
dataset.samples

[QueryAnswerSample(query='What is a hedge?', expected_answer='An investment or contract intended to reduce the risk of adverse price movements in another asset. Common hedging instruments include futures, options, and currency forwards.'),
 QueryAnswerSample(query="What does 'underwriting' mean in insurance?", expected_answer='The process by which an insurer evaluates the risk of insuring an applicant, decides whether to offer coverage, and at what price and terms.'),
 QueryAnswerSample(query='What is 7 factorial (7!)?', expected_answer='5040'),
 QueryAnswerSample(query='Can my insurer cancel my policy after a claim?', expected_answer='Mid-term cancellation is usually limited to specific reasons (fraud, non-payment, material misrepresentation). At renewal, the insurer may decline to renew based on claims history, subject to local regulation.'),
 QueryAnswerSample(query='What is EBITDA?', expected_answer='Earnings Before Interest, Taxes, Depreciation, and Amortization. A proxy for operating cash flow used to compare profitability across companies with different capital structures.'),
 QueryAnswerSample(query='What is the sum of angles in a triangle?', expected_answer='180 degrees'),
 QueryAnswerSample(query='How do you serialize a Python dict to a JSON string?', expected_answer='import json\\njson.dumps(my_dict)  # add ensure_ascii=False for non-ASCII; indent=2 for pretty-printing'),
 QueryAnswerSample(query="What is 'loss adjustment expense' (LAE)?", expected_answer='Costs the insurer incurs to investigate, defend, and settle claims—e.g., adjuster fees, legal expenses—separate from the indemnity paid on the claim itself.'),
 QueryAnswerSample(query='Write a Python dict comprehension that maps each word in a list to its length.', expected_answer='{w: len(w) for w in words}'),
 QueryAnswerSample(query='What is beta in finance?', expected_answer="A measure of a stock's volatility relative to the market. Beta = 1 means it moves with the market; >1 more volatile; <1 less; negative betas move opposite the market on average."),
 QueryAnswerSample(query='Write a Python context manager that times the code inside it.', expected_answer="from contextlib import contextmanager\\nimport time\\n\\n@contextmanager\\ndef timer(label='block'):\\n    t0 = time.perf_counter()\\n    yield\\n    print(f'{label}: {time.perf_counter() - t0:.4f}s')"),
 QueryAnswerSample(query="What is a 'release' in claim settlement?", expected_answer='A document the claimant signs agreeing to accept the settlement amount in full satisfaction of the claim, releasing the insurer (and often the responsible party) from further liability for the loss.'),
 QueryAnswerSample(query='What is market capitalization?', expected_answer="The total market value of a company's outstanding shares: share price multiplied by number of shares outstanding. Used to size companies as small-, mid-, or large-cap."),
 QueryAnswerSample(query="What is 'loss of use' coverage?", expected_answer='Reimburses additional living expenses (e.g., hotel, restaurants) if your home becomes uninhabitable due to a covered loss—up to a defined limit and time period.'),
 QueryAnswerSample(query="What is a 'depreciation holdback'?", expected_answer='Under replacement-cost coverage, the insurer first pays ACV (actual cash value); the depreciation portion is paid only after the insured completes the repair or replacement and submits proof.'),
 QueryAnswerSample(query='What is the smallest unit of life?', expected_answer='The cell.'),
 QueryAnswerSample(query='Write a SQL query to count the number of customers per country in a `customers` table.', expected_answer='SELECT country, COUNT(*) AS customer_count\\nFROM customers\\nGROUP BY country\\nORDER BY customer_count DESC;'),
 QueryAnswerSample(query="What is 'pet insurance'?", expected_answer='A policy reimbursing veterinary costs for accidents, illnesses, and—depending on plan—routine care, after a deductible and subject to limits and exclusions.'),
 QueryAnswerSample(query='What language has the most native speakers?', expected_answer='Mandarin Chinese has the most native speakers worldwide.'),
 QueryAnswerSample(query='Compute the monthly payment on a $200,000 mortgage at a 5% annual rate over 30 years.', expected_answer='About $1,073.64 per month. Using M = P*r/(1-(1+r)^-n) with P=200000, r=0.05/12, n=360.'),
 QueryAnswerSample(query='What is a list comprehension and when should you use one?', expected_answer='A concise expression for building a list from an iterable: `[expr for x in iterable if cond]`. Use it for simple transformations and filters; for complex logic prefer a regular for-loop for readability.'),
 QueryAnswerSample(query='What is the slope of the line y = 3x + 2?', expected_answer='3'),
 QueryAnswerSample(query='How do you reverse a string in Python in one line?', expected_answer='Use slicing: s[::-1]'),
 QueryAnswerSample(query='What is the capital of Canada?', expected_answer='Ottawa.'),
 QueryAnswerSample(query='What is a balance sheet?', expected_answer="A financial statement showing a company's assets, liabilities, and shareholders' equity at a single point in time. Assets always equal liabilities plus equity."),
 QueryAnswerSample(query='What is the difference between a stack and a queue?', expected_answer='A stack is LIFO (last-in, first-out): push/pop at the same end. A queue is FIFO (first-in, first-out): enqueue at the back, dequeue at the front.'),
 QueryAnswerSample(query='What is a mutual fund?', expected_answer='An investment vehicle that pools money from many investors to buy a diversified portfolio managed by a professional. Investors hold shares of the fund and trade at end-of-day NAV.'),
 QueryAnswerSample(query='What is the difference between a Roth IRA and a traditional IRA?', expected_answer='Traditional IRA: contributions may be tax-deductible, withdrawals in retirement are taxed. Roth IRA: contributions are after-tax, qualified withdrawals are tax-free. Income limits and rules differ.'),
 QueryAnswerSample(query='What is the capital of France?', expected_answer='Paris'),
 QueryAnswerSample(query='What is a credit score?', expected_answer="A numeric rating (commonly 300-850 in the U.S.) summarizing a person's creditworthiness based on payment history, credit utilization, length of history, mix, and new credit."),
 QueryAnswerSample(query='How do catastrophe (CAT) claims differ from regular ones?', expected_answer='CAT claims involve large-scale events (hurricanes, earthquakes, wildfires) generating many simultaneous claims. Insurers deploy CAT teams, may apply special CAT deductibles, and adjusting timelines often stretch.'),
 QueryAnswerSample(query='What is the largest ocean on Earth?', expected_answer='The Pacific Ocean.'),
 QueryAnswerSample(query='Who wrote Romeo and Juliet?', expected_answer='William Shakespeare'),
 QueryAnswerSample(query='What is the largest desert in the world?', expected_answer='Antarctica is the largest desert by area, classified as a polar desert. Among hot deserts, the Sahara is the largest.'),
 QueryAnswerSample(query='What is the formula for the volume of a sphere?', expected_answer='V = (4/3)πr³'),
 QueryAnswerSample(query='What is the chemical symbol for gold?', expected_answer='Au'),
 QueryAnswerSample(query='What is REST?', expected_answer='Representational State Transfer: an architectural style for networked APIs using stateless HTTP methods (GET, POST, PUT, PATCH, DELETE) on resources identified by URLs, typically returning JSON.'),
 QueryAnswerSample(query='What is a Python generator?', expected_answer='A function that uses `yield` to produce values lazily, one at a time. It maintains its state between calls and is memory-efficient for large or infinite sequences.'),
 QueryAnswerSample(query='What is leverage in finance?', expected_answer='Using borrowed capital to increase potential return on investment. Leverage amplifies both gains and losses and increases risk if the underlying investment underperforms.'),
 QueryAnswerSample(query="What is 'lapse' of an insurance policy?", expected_answer='Termination of the policy because the insured failed to pay the premium by the end of the grace period. Coverage ceases until the policy is reinstated, if allowed.'),
 QueryAnswerSample(query='What is the unit of electrical resistance?', expected_answer='The ohm (Ω).'),
 QueryAnswerSample(query='What is an IRA?', expected_answer='Individual Retirement Account: a U.S. tax-advantaged personal retirement account. Traditional IRAs offer tax-deferred growth; Roth IRAs offer tax-free growth on after-tax contributions.'),
 QueryAnswerSample(query="What is 'umbrella insurance'?", expected_answer='A policy providing extra liability coverage above the limits of underlying policies (auto, home), and sometimes covering claims excluded by them, such as libel or slander.'),
 QueryAnswerSample(query='What is a SQL injection and how do you prevent it?', expected_answer='An attack where untrusted input is concatenated into SQL, letting attackers run arbitrary queries. Prevent it by using parameterized queries or prepared statements, never string concatenation, and by applying least-privilege database accounts.'),
 QueryAnswerSample(query='What is the difference between a first-party and a third-party claim?', expected_answer="A first-party claim is filed by the policyholder against their own insurer for their own loss. A third-party claim is filed by someone else against the policyholder's liability insurance for damage the policyholder caused."),
 QueryAnswerSample(query='What does NATO stand for?', expected_answer='North Atlantic Treaty Organization.'),
 QueryAnswerSample(query='What if two insurance policies cover the same loss?', expected_answer="The policies' 'other insurance' clauses determine the order of payment—primary, excess, or pro rata. Insurers coordinate so the insured isn't paid twice for the same loss (per the indemnity principle)."),
 QueryAnswerSample(query='Should I get my own repair estimate after an auto claim?', expected_answer="Yes—an independent estimate from a trusted repair shop helps verify the insurer's appraisal, supports negotiations if the offer seems low, and gives a clearer view of repair quality and timelines."),
 QueryAnswerSample(query='What is the largest organ in the human body?', expected_answer='The skin.'),
 QueryAnswerSample(query='Write a Python function that returns the GCD of two integers.', expected_answer='from math import gcd\\n# Or implement it:\\n# def gcd(a, b):\\n#     while b:\\n#         a, b = b, a % b\\n#     return abs(a)'),
 QueryAnswerSample(query='What is the difference between gross and net income?', expected_answer='Gross income is total revenue minus the direct cost of producing goods/services (COGS). Net income subtracts all remaining expenses—operating costs, interest, taxes—giving the bottom-line profit.'),
 QueryAnswerSample(query='What is the mean of 4, 8, 15, 16, 23, 42?', expected_answer='Mean = (4+8+15+16+23+42)/6 = 108/6 = 18.'),
 QueryAnswerSample(query="What is 'disability insurance'?", expected_answer="Coverage that replaces a portion of the insured's income if they become unable to work due to illness or injury. Short-term and long-term variants exist."),
 QueryAnswerSample(query="Who wrote 'The Origin of Species'?", expected_answer='Charles Darwin, published in 1859.'),
 QueryAnswerSample(query="What is a 'binder' in insurance?", expected_answer='A temporary written agreement issued by the insurer or agent that provides immediate coverage while the formal policy is being prepared. Usually valid for a short period.'),
 QueryAnswerSample(query="What does 'totaled' mean in auto insurance?", expected_answer='A vehicle is declared a total loss when the cost of repair exceeds a percentage of its actual cash value (often 70-80%, varying by jurisdiction and insurer). The insurer pays the ACV minus deductible and takes the salvage.'),
 QueryAnswerSample(query='Solve for x: 2x + 3 = 11.', expected_answer='x = 4. Subtract 3 from both sides to get 2x = 8, then divide by 2.'),
 QueryAnswerSample(query='How do you remove duplicates from a Python list while preserving order?', expected_answer='Use a dict: list(dict.fromkeys(my_list)). Since Python 3.7, dict preserves insertion order, so this is concise and order-preserving.'),
 QueryAnswerSample(query='What is the powerhouse of the cell?', expected_answer="The mitochondrion (often called the 'powerhouse of the cell' because it produces most of the cell's ATP)."),
 QueryAnswerSample(query='What is the difference between INNER JOIN and LEFT JOIN in SQL?', expected_answer='INNER JOIN returns only rows where the join condition matches in both tables. LEFT JOIN returns all rows from the left table and matching rows from the right table; non-matching right rows yield NULLs.'),
 QueryAnswerSample(query='What is diversification?', expected_answer='Spreading investments across assets, sectors, and regions so that idiosyncratic risks partially offset, reducing overall portfolio volatility without proportionally lowering expected return.'),
 QueryAnswerSample(query="What is a 'waiting period' in insurance?", expected_answer='A defined time after policy issuance during which certain claims are not payable. Common in disability, dental, and some health policies.'),
 QueryAnswerSample(query='What is the square root of 144?', expected_answer='12'),
 QueryAnswerSample(query="What is 'health insurance' in one sentence?", expected_answer="A contract under which an insurer pays some or all of the policyholder's medical expenses in exchange for a premium, subject to deductibles, copays, coinsurance, and exclusions."),
 QueryAnswerSample(query='What is the smallest country in the world?', expected_answer='Vatican City.'),
 QueryAnswerSample(query="What is an 'occurrence' policy?", expected_answer='A liability policy that covers incidents that occur during the policy period, even if the claim is filed years later, as long as the loss happened while the policy was in force.'),
 QueryAnswerSample(query='How many planets are in our solar system?', expected_answer='Eight, since Pluto was reclassified as a dwarf planet in 2006.'),
 QueryAnswerSample(query="What does 'IBNR' stand for in insurance?", expected_answer='Incurred But Not Reported. The estimated reserve for losses that have already occurred but have not yet been reported to the insurer. A core actuarial reserving concept.'),
 QueryAnswerSample(query='What is net present value (NPV)?', expected_answer='The sum of discounted cash flows of an investment minus its initial cost. A positive NPV at the chosen discount rate means the investment is expected to add value.'),
 QueryAnswerSample(query='Write a JavaScript function that returns the unique values of an array.', expected_answer='const unique = arr => [...new Set(arr)];'),
 QueryAnswerSample(query='What does the SQL keyword UNION do?', expected_answer='It combines the result sets of two queries with the same column shape, removing duplicates. Use UNION ALL to keep duplicates and run faster.'),
 QueryAnswerSample(query="What is 'flood insurance' typically excluded from?", expected_answer='Standard homeowners policies, which usually exclude flood damage. Coverage is purchased separately, often through national flood programs.'),
 QueryAnswerSample(query='Write a Python snippet that opens a CSV file and prints each row.', expected_answer="import csv\\nwith open('data.csv', newline='', encoding='utf-8') as f:\\n    for row in csv.reader(f):\\n        print(row)"),
 QueryAnswerSample(query="What is a 'proof of loss'?", expected_answer='A formal sworn statement from the insured detailing the loss—date, cause, items damaged, and amount claimed—submitted to support a claim. Most policies require it within a defined timeframe.'),
 QueryAnswerSample(query="What is an 'exclusion' in an insurance policy?", expected_answer='A specific condition, peril, or situation that the policy does not cover. Exclusions are listed in the policy and are enforceable when a claim falls within them.'),
 QueryAnswerSample(query="What is Newton's second law of motion?", expected_answer='Force equals mass times acceleration: F = m * a.'),
 QueryAnswerSample(query='Write a JavaScript function that debounces another function with a given delay in ms.', expected_answer='function debounce(fn, delay) {\\n  let t;\\n  return (...args) => {\\n    clearTimeout(t);\\n    t = setTimeout(() => fn(...args), delay);\\n  };\\n}'),
 QueryAnswerSample(query='Write a Python list comprehension that returns the squares of even numbers from 0 to 20.', expected_answer='[x*x for x in range(21) if x % 2 == 0]'),
 QueryAnswerSample(query='What is a credit spread?', expected_answer='The difference in yield between a corporate (or other risky) bond and a comparable-maturity government benchmark. It reflects compensation for default risk.'),
 QueryAnswerSample(query='What is correlation in finance?', expected_answer="A statistic between -1 and 1 measuring how two assets' returns move together. Combining low- or negatively-correlated assets reduces portfolio volatility."),
 QueryAnswerSample(query='What is the tallest mountain in the world?', expected_answer='Mount Everest, with a summit at about 8,849 meters above sea level.'),
 QueryAnswerSample(query="What is 'mitigation of damages' duty?", expected_answer="The insured's duty to take reasonable steps to limit further damage after a loss—e.g., tarping a roof after a storm. Failure to mitigate can reduce or void the claim."),
 QueryAnswerSample(query='Explain photosynthesis in one sentence.', expected_answer='Photosynthesis is the process by which plants, algae, and some bacteria convert sunlight, water, and carbon dioxide into glucose and oxygen.'),
 QueryAnswerSample(query='What is a structured settlement?', expected_answer='A negotiated arrangement where claim proceeds are paid as a stream of periodic payments (often via an annuity) instead of a lump sum. Common in large bodily-injury settlements.'),
 QueryAnswerSample(query='How do I dispute the value placed on my totaled car?', expected_answer='Get independent appraisals, comparable listings of similar vehicles for sale in your area, and submit them to the insurer. Many policies offer an appraisal clause to invoke a third-party umpire if disagreement persists.'),
 QueryAnswerSample(query='What is an annuity?', expected_answer='A financial product paying a stream of cash flows over time. Common in retirement, where an insurer pays the holder periodic income in exchange for a lump sum or premiums.'),
 QueryAnswerSample(query='What is depreciation?', expected_answer='An accounting method that allocates the cost of a tangible asset over its useful life, reflecting wear, tear, and obsolescence on the income statement.'),
 QueryAnswerSample(query='Can filing a claim raise my premium?', expected_answer='Often yes, especially for at-fault auto accidents or multiple property claims in a short period. Insurers price based on risk, and claim history is a strong signal. No-fault and informational-only claims may have less or no impact.'),
 QueryAnswerSample(query='What does `async/await` do in JavaScript?', expected_answer='`async` marks a function as returning a Promise. `await` pauses execution inside an async function until a Promise settles, letting you write asynchronous code in a synchronous-looking style.'),
 QueryAnswerSample(query='What is the difference between a virus and a bacterium?', expected_answer="Bacteria are single-celled living organisms that can reproduce on their own. Viruses are much smaller, are not considered fully alive, and require a host cell's machinery to replicate."),
 QueryAnswerSample(query="What is the most abundant gas in Earth's atmosphere?", expected_answer='Nitrogen (about 78% by volume).'),

In [7]:
result_dataset = run_multi_model_evaluation(dataset, models)

[CACHE MISS] mistral
[CACHE MISS] gemma2
{"timestamp": "2026-05-09T08:47:33.504477", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:33.504903", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:41.186373", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:41.187446", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:42.107930", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:42.109380", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:47.250725", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:47.252163", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:47.312063", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:47.313208", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:48.155976", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:48.156538", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:48.826426", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:48.827855", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:52.437866", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:52.439323", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:53.030826", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:53.032162", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:58.486401", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:58.487516", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:59.489450", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:47:59.490380", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:01.324138", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:01.325467", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:01.770712", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:01.772032", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:06.002628", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:06.003501", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:07.218027", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:07.219433", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:19.187261", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:19.188113", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:19.213796", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:19.214863", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:20.309495", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:20.311261", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:21.349740", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:21.350743", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:26.187132", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:26.188104", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:26.883634", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:26.884838", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:32.195346", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:32.196756", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:33.208943", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:33.210318", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:34.055893", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:34.057194", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:34.134066", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:34.135351", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:34.753237", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:34.754885", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:35.167377", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:35.167866", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:39.777306", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:39.778766", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:40.518714", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:40.520101", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:45.905273", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:45.906560", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:46.577436", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:46.578346", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:47.723272", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:47.724648", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:48.729152", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:48.730489", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:56.574133", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:56.575038", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:57.631192", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:48:57.633486", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:03.866528", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:03.867987", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:05.030859", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:05.032102", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:06.676225", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:06.677054", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:07.631862", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:07.633193", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:12.925524", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:12.926860", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:13.667366", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:13.668073", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:14.015092", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:14.016364", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:14.823002", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:14.824450", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:25.499672", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:25.502056", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:26.537730", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:26.539002", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:30.004107", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:30.005460", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:31.242049", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:31.243498", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:32.568305", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:32.569494", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:33.310553", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:33.311906", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:41.464671", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:41.466254", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:42.346041", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:42.347388", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:47.434724", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:47.436124", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:48.124428", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:48.125000", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:53.078706", "level": "INFO", "message": "Inference completed model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:53.080237", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:54.649054", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:54.650332", "level": "INFO", "message": "Starting inference with model=gemma2", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:55.681212", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:55.682757", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:56.500293", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:49:56.501968", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:50:02.989321", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:50:02.990666", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:50:03.801803", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:50:03.802811", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:50:06.957863", "level": "INFO", "message": "Inference completed model=mistral", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:50:06.958897", "level": "INFO", "message": "Starting inference with model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:50:07.562428", "level": "INFO", "message": "Inference completed model=llama3", "module": "ollama_client", "request_id": "unknown"}
{"timestamp": "2026-05-09T08:50:07.563762", "level": "INFO", "message": "Starting inference with model=mistral", "module": "ollama_client", "request_id": "unknown"}

In [8]:
result_dataset.inferences["mistral"]

[InferenceResult(generated_answer=' In finance, a hedge refers to an investment or trading strategy that is intended to offset potential losses in another investment. The goal of hedging is to reduce the risk of adverse price movements in an asset, portfolio, or position.\n\nHedging strategies can be used for various purposes such as:\n\n1. Protecting against fluctuations in exchange rates (currency hedging)\n2. Guarding against changes in interest rates (interest rate hedging)\n3. Mitigating risks associated with commodity prices (commodity hedging)\n4. Reducing volatility due to market uncertainty or unforeseen events (risk management)\n\nFor example, an airline may enter into a currency hedge agreement to protect against fluctuations in the exchange rate between their local currency and the currencies they purchase fuel from. This helps them maintain a steady cost for their operations even if the exchange rate changes significantly during the contract period.', latency_seconds=7.682900905609131, token_count=199, correctness=0.9),
 InferenceResult(generated_answer=" In the context of insurance, underwriting refers to the process by which an insurance company evaluates the acceptance of an applicant and determines appropriate coverage, premiums, and risks for a particular insurance policy. The underwriting process involves assessing various factors such as the insured's age, health status, lifestyle, occupation, and other relevant details to evaluate the risk profile of the potential client. Based on this assessment, the insurance company will decide whether to issue the policy, decline it, or offer coverage with different terms and conditions, including premiums. The goal of underwriting is to ensure that the insurance company can accurately price and manage the risks associated with the policies they issue.", latency_seconds=5.2038798332214355, token_count=139, correctness=1.0),
 InferenceResult(generated_answer=' Factorial of a number is the product of all positive integers up to that number. So, for 7 factorial (denoted as 7!), we multiply all numbers from 1 to 7:\n\n7! = 7 * 6 * 5 * 4 * 3 * 2 * 1\n= 5040\n\nSo, 7 factorial is equal to 5040.', latency_seconds=3.6114377975463867, token_count=96, correctness=1.0),
 InferenceResult(generated_answer=' Yes, an insurance company can potentially cancel your policy after a claim, but only under certain circumstances. This is often referred to as "non-renewal" or "cancellation for cause."\n\nHere are some reasons why an insurer might decide to cancel a policy after a claim:\n\n1. Fraud: If the insurance company suspects that you have committed fraud, either by lying on your application or exaggerating a claim, they may choose to terminate your policy.\n2. High risk: If you file multiple claims within a short period of time or make claims for expensive items, the insurer might decide that your policy is too risky and cancel it.\n3. Policy terms and conditions: Each insurance policy has specific terms and conditions. If you have violated any of these terms (for example, by not disclosing relevant information when applying for the policy), the insurer can potentially cancel your coverage.\n4. Bankruptcy or insolvency: If the insurance company goes bankrupt or becomes insolvent, they may be forced to cancel all policies.\n5. Policy expiration: If your policy has reached its end date, the insurer can choose not to renew it. However, they are required to give you notice before the policy expires.\n\nIt\'s important to note that insurance companies must follow specific rules and regulations when canceling a policy, and these rules vary depending on the jurisdiction and the type of insurance (e.g., health, auto, home). Always consult with your insurance provider or a legal professional for advice tailored to your situation.', latency_seconds=12.971415996551514, token_count=333, correctness=0.8),
 InferenceResult(generated_answer=" EBITDA stands for Earnings Before Interest, Taxes, Depreciation, and Amortization. It's a financial metric used to measure a company's operating performance and cash flow, excluding certain expenses that can vary between companies or industries.\n\nHere's a breakdown of each component in EBITDA:\n\n1. Earnings (or net income) - The total profit or loss after all operating costs, interest, taxes, and extraordinary items have been accounted for.\n2. Interest - The cost of borrowing money, typically calculated as the interest expense on debt obligations.\n3. Taxes - The amount paid to government entities in the form of corporate income tax and other taxes.\n4. Depreciation - A non-cash expense that represents the wearing out or consumption of assets over time.\n5. Amortization - A non-cash expense used to account for the gradual reduction (amortization) of intangible assets like patents, trademarks, and goodwill over their estimated useful lives.\n\nEBITDA is often used by investors and analysts to compare companies with different capital structures, as it eliminates the effects of financing decisions (interest expenses) and accounting choices (depreciation and amortization). However, it's important to remember that EBITDA does not provide a complete picture of a company's financial condition, as it excludes essential items like taxes, interest payments, and long-term asset maintenance costs.", latency_seconds=11.995500087738037, token_count=317, correctness=0.9),
 InferenceResult(generated_answer=' The sum of angles in a triangle always adds up to 180 degrees in a flat (Euclidean) plane, or 360 degrees in a spherical triangle. This is a fundamental theorem in Euclidean geometry and is known as the Exterior Angle Theorem. In the case of a spherical triangle on a sphere (for example, triangles drawn on Earth), the sum of angles is 360 degrees due to the curvature of the surface. However, for triangles drawn on a flat plane like paper, the sum of angles is always 180 degrees.', latency_seconds=4.837384939193726, token_count=128, correctness=0.5),
 InferenceResult(generated_answer=' In Python, you can convert a dictionary to a JSON string using the `json.dumps()` function from the json module. Here\'s an example:\n\n```python\nimport json\n\ndata = {"key1": "value1", "key2": 2, "key3": [1, 2, 3]}\njson_string = json.dumps(data)\nprint(json_string)\n```\n\nIn this example, `data` is a Python dictionary, and `json.dumps()` converts it to a JSON string, which is then printed out. The resulting JSON string would look like this:\n\n```json\n{"key1": "value1", "key2": 2, "key3": [1, 2, 3]}\n```', latency_seconds=7.172343015670776, token_count=178, correctness=0.75),
 InferenceResult(generated_answer=' "Loss Adjustment Expense" (LAE) refers to the costs that an insurance company incurs when investigating, settling, and paying claims to policyholders. These expenses can include fees for adjusters, attorneys, appraisers, and other professionals who help determine the extent of the insured\'s loss and the amount of the claim payment. LAE is a critical component in calculating the ultimate cost of claims for the insurance company. It\'s important to note that LAE is not a part of the original claim amount but rather an additional expense that the insurance company bears as part of processing claims.', latency_seconds=5.023798942565918, token_count=130, correctness=0.9),
 InferenceResult(generated_answer=' Sure! Here is an example of a Python dictionary comprehension that maps each word in a list to its length:\n\n```python\nwords = ["apple", "banana", "cherry", "date"]\nword_lengths = {word: len(word) for word in words}\nprint(word_lengths)\n```\n\nIn this example, `word_lengths` is a dictionary that maps each word from the list `words` to its length. The output of the code would be:\n\n```\n{\'apple\': 5, \'banana\': 6, \'cherry\': 6, \'date\': 4}', latency_seconds=5.386487245559692, token_count=143, correctness=0.9),
 InferenceResult(generated_answer=" In finance, Beta (β) is a measure of the riskiness of an asset compared to the market as a whole. It's a key concept in Modern Portfolio Theory developed by Harry Markowitz.\n\nBeta represents the sensitivity of an individual asset or portfolio's return to market movements. A beta of 1 means that the asset's price will move with the market, a beta greater than 1 indicates the asset is riskier and more volatile than the market (it moves up and down more), while a beta less than 1 suggests the asset is less risky and has a lower volatility (it moves up and down less) compared to the market.\n\nFor example, if an investment's beta is 2.0, it tends to move $2 for every $1 move in the market index. If the beta is 0.5, it only tends to move $0.50 for every $1 move in the market index.\n\nIt's important to note that Beta is calculated using historical data and doesn't guarantee future performance. It's most commonly used with stocks, but can also be applied to other investment assets like bonds or real estate.", latency_seconds=9.996769905090332, token_count=253, correctness=0.95),
 InferenceResult(generated_answer=' Here\'s a simple Python context manager that times the code within it and prints the execution time:\n\n```python\nimport time\n\ndef timer():\n    def decorator(func):\n        def wrapper(*args, **kwargs):\n            start_time = time.time()\n            result = func(*args, **kwargs)\n            end_time = time.time()\n            print(f\'Function "{func.__name__}" took {end_time - start_time:.4f} seconds to execute.\')\n            return result\n        return wrapper\n    return decorator\n\n@timer()\ndef some_function():\n    # Your code here\n    pass\n```\n\nIn this example, `some_function()` is the function that you want to time. When calling the decorated function with `@timer()`, it will automatically calculate and print the execution time.\n\nYou can use it as follows:\n\n```python\nif __name__ == "__main__":\n    some_function()\n```', latency_seconds=9.04364800453186, token_count=226, correctness=0.2),
 InferenceResult(generated_answer=' In the context of insurance claims, a "release" refers to a legal document that is signed by both the insured and the insurance company, typically at the end of the claim process. The release signifies that the insurance company has settled the claim and paid any owed amounts, and the insured releases the insurance company from further liability related to the incident or loss covered by the claim.\n\nThe release document usually includes a clause stating that the insured will not sue the insurance company for additional compensation related to the same event or loss. It\'s essential to carefully review the terms of the release before signing, as it may impact future claims and any potential legal rights. If you have specific questions about a release in your claim settlement, consulting with an attorney can help ensure that you fully understand its implications.', latency_seconds=6.3831400871276855, token_count=165, correctness=0.9),
 InferenceResult(generated_answer=' Market capitalization, often referred to as "market cap," is a metric used to measure the total market value of a company\'s outstanding shares of stock. It is calculated by multiplying a company\'s share price by its total number of outstanding shares.\n\nMarket capitalization provides investors with an easy way to compare the sizes of different companies, regardless of their industry or location. Companies are typically categorized as small-cap, mid-cap, or large-cap based on their market capitalization:\n\n1. Small-Cap (less than $2 billion): These companies are generally more risky but have high growth potential. They often operate in niche markets and may be younger or smaller compared to other public companies.\n\n2. Mid-Cap ($2 billion to $10 billion): Mid-sized companies offer a balance of growth potential and stability. They tend to have established positions in their respective industries and may show steady profit growth.\n\n3. Large-Cap (over $10 billion): These are well-established, large companies that often dominate their markets. They may have a diverse product or service portfolio, strong brand recognition, and consistent financial performance.\n\nUnderstanding market capitalization is essential when making investment decisions as it helps investors to identify the risk profile of potential investments and compare them with other companies in the same sector.', latency_seconds=10.677595853805542, token_count=283, correctness=0.9),
 InferenceResult(generated_answer=' "Loss of use" coverage, also known as "additional living expense" coverage, is a type of insurance provision that helps policyholders pay for additional costs incurred when they cannot live in their home due to damage covered by their insurance policy. This could be caused by events such as fire, storm, or other disasters. The coverage typically helps with expenses like hotel bills, restaurant meals, and rentals for temporary living quarters, storage for personal property, and other related costs that occur because the insured cannot live in their home while it is being repaired or rebuilt. It\'s important to note that the specific details can vary depending on the insurance policy and the jurisdiction.', latency_seconds=6.030493259429932, token_count=143, correctness=0.9),
 InferenceResult(generated_answer=' A depreciation holdback refers to a portion of the purchase price that is withheld during the sale of an asset, such as property or equipment, to account for potential future depreciation costs. The purpose of this practice is to protect the buyer from unexpected expenses related to the depreciation of the asset over time.\n\nFor example, in a real estate transaction, the seller may agree to withhold a certain percentage of the sale price and place it in escrow for a specific period, usually several years. This amount can be used later to make repairs or improvements to the property if depreciation-related issues arise during that time. After the agreed-upon period, the holdback funds are typically released back to the seller.\n\nThe specific terms of a depreciation holdback, including the percentage withheld and the duration of the escrow period, are negotiable between the buyer and seller. This provision can help reduce the risk for buyers when purchasing assets that may require significant ongoing maintenance or upkeep.', latency_seconds=8.15434193611145, token_count=217, correctness=0.4),
 InferenceResult(generated_answer=" The smallest unit of life that can independently exist and reproduce on its own is called a cell. Cells are the basic structural and functional units of all known living organisms. However, if we're talking about the smallest subunit that still maintains some characteristics of a cell, it would be the organelle or the cellular organelle. These are specialized structures within cells that have specific functions to help the cell survive and function optimally. Examples include mitochondria, ribosomes, and chloroplasts. If we further break down these organelles, we enter the realm of biochemistry rather than biology.", latency_seconds=5.088703870773315, token_count=132, correctness=0.8),
 InferenceResult(generated_answer=" To write a SQL query that counts the number of customers per country from a `customers` table, you can use the `GROUP BY` statement combined with the `COUNT()` function. Here's an example using hypothetical column names and table structure:\n\n```sql\nSELECT country, COUNT(customer_id) AS customer_count\nFROM customers\nGROUP BY country;\n```\n\nIn this query, replace `country` with the actual column name that stores the country of each customer, and `customer_id` with the column that uniquely identifies each customer. The `AS` keyword is used to rename the resulting column as `customer_count`. This SQL statement groups all customers by their countries and calculates the count for each group, displaying the results in a tabular format.", latency_seconds=7.557624101638794, token_count=174, correctness=0.8),
 InferenceResult(generated_answer=" Pet insurance is a type of insurance that provides coverage for veterinary expenses incurred by the pet owner. Just like human health insurance, pet insurance can help cover costs associated with illnesses, injuries, or accidents that may occur to pets.\n\nThere are different types of policies available, but generally, they cover costs related to vet bills, prescription medications, surgery, hospitalization, and sometimes even dental care and alternative therapies. Some policies also offer coverage for loss due to theft or death of the pet.\n\nThe cost of the policy depends on various factors including the type of pet (dogs and cats are most commonly insured), the pet's age, breed, location, and the specific plan chosen. It's important to carefully review the policy details before purchasing to ensure it meets your needs and budget.", latency_seconds=6.488686800003052, token_count=169, correctness=0.7),
 InferenceResult(generated_answer=" As of now, Mandarin Chinese is considered to have the most native speakers worldwide. According to Ethnologue, an online database of languages, about 1 billion people speak Mandarin as their first language. However, it's important to note that language usage can vary, and the number of speakers can change over time due to factors like migration, globalization, and population growth.", latency_seconds=3.1560821533203125, token_count=80, correctness=0.9),
 InferenceResult(generated_answer=' To calculate the monthly mortgage payment, we can use the formula for an amortizing loan:\n\nMonthly Payment (P) = P[r(1+r)^n] / [(1+r)^n-1]\n\nWhere:\n- P is the principal amount ($200,000 in this case)\n- r is the monthly interest rate (annual rate divided by 12)\n- n is the number of payments (360 for a 30-year mortgage)\n\nGiven an annual interest rate of 5%, the monthly interest rate would be:\n\nr = 0.05 / 12 = 0.0041667\n\nNow, we can calculate the monthly payment using the formula above:\n\nMonthly Payment (P) = $200,000[0.0041667(1+0.0041667)^360] / [(1+0.0041667)^360 - 1]\n\nMonthly Payment (P) = $981.72\n\nSo, the monthly payment on a $200,000 mortgage at a 5% annual rate over 30 years is approximately $981.72.', latency_seconds=11.708853006362915, token_count=292, correctness=0.96),

In [9]:
result_dataset.inferences["gemma2"]

[InferenceResult(generated_answer='A hedge can have a few different meanings depending on the context:\n\n**1. Financial Hedge:** \nThis is the most common meaning. In finance, a hedge is an investment position taken to reduce the risk of adverse price movements in another asset. Imagine you own stock in a company that makes winter coats. If you think the price of wool might go up, making your coats more expensive to produce, you could buy futures contracts on wool. This would "hedge" your position against rising wool prices because if wool prices do go up, the value of your futures contract would also increase, offsetting some of your losses from the higher production costs.\n\n**2. Literal Hedge:** \nThis is a row of shrubs or trees planted close together to create a barrier for privacy or security.\n\n**3. Legal/Business Hedge:**  A hedge can also refer to a strategy used in business or law to minimize risk or liability. For example, a company might enter into contracts that protect them from price fluctuations in raw materials.\n\n**Key characteristics of a financial hedge:**\n\n\n* **Reduces risk:** The primary goal of hedging is to limit potential losses.\n* **Offsetting positions:** Hedging often involves taking an opposite position in a related asset market.\n* **Not guaranteed:** While hedges can reduce risk, they don\'t eliminate it entirely.\n\nIf you provide more context about how you encountered the term "hedge," I can give you a more specific answer!', latency_seconds=13.747304201126099, token_count=300, correctness=0.7),
 InferenceResult(generated_answer="Underwriting in insurance is the process of **evaluating risk** and deciding whether to offer coverage, at what price (premium), and under what terms.  \n\nThink of it like this: \n\n* An insurance company wants to predict how likely someone is to make a claim.\n* Underwriters are the experts who analyze applications, medical records, driving history, financial information, and other factors to assess that risk.\n* Based on their evaluation, they decide:\n\n    * **To accept the application:** The person gets insured at a specific premium based on their risk level.  Higher risk usually means a higher premium.\n    * **To decline the application:** The person is deemed too risky for the insurance company to cover.\n    * **To offer coverage with modifications:** This could include charging a higher premium, excluding certain types of coverage, or requiring additional safeguards.\n\n**Essentially, underwriting is the foundation of how insurance companies manage risk and stay profitable.**  It's a crucial process that ensures the right people get insured at fair prices while protecting the insurer from catastrophic losses.", latency_seconds=10.330981731414795, token_count=222, correctness=0.9),
 InferenceResult(generated_answer='7! (7 factorial) is:\n\n7 * 6 * 5 * 4 * 3 * 2 * 1 = **5040** \n', latency_seconds=1.8350269794464111, token_count=38, correctness=1.0),
 InferenceResult(generated_answer="It depends on your specific insurance policy and the circumstances surrounding the claim. \n\n**Here's a general overview:**\n\n* **Non-Renewal:** Most insurers can choose not to renew your policy after it expires, even if you filed a claim. They may do this based on various factors like your claims history, driving record (for auto insurance), or credit score. You will usually receive notice well in advance of your policy's expiration date.\n* **Policy Cancellation:** \n\nInsurers can typically cancel your policy for specific reasons, regardless of whether you filed a claim. These reasons often include:\n\n* **Non-payment of premiums:** This is the most common reason for cancellation.\n* **Material misrepresentation on your application:** If you provided false information when applying for insurance, the insurer may cancel your policy.\n* **Fraudulent claims:** Filing a fraudulent claim will almost certainly lead to cancellation.\n* **Violation of policy terms:** Engaging in activities prohibited by your policy, such as driving under the influence, can result in cancellation.\n\n* **Claim-Specific Cancellation:** Some policies specifically state that filing a certain type of claim (e.g., multiple claims within a short period) may lead to cancellation.\n\n\n**Important Notes:**\n\n* **Review your policy documents carefully:** Pay close attention to the sections regarding non-renewal, cancellation, and specific reasons for termination.\n* **Communicate with your insurer:** If you have concerns about your policy or a recent claim, reach out to your insurer directly to discuss your situation.\n* **Shop around for other insurers:** If your current insurer cancels your policy, don't panic. You can explore options with other insurance companies.\n\n\nRemember, laws and regulations regarding insurance cancellation vary by state. Consulting with an insurance agent or attorney in your area can provide more specific guidance based on your circumstances.", latency_seconds=17.416100025177002, token_count=380, correctness=0.8),
 InferenceResult(generated_answer="EBITDA stands for **Earnings Before Interest, Taxes, Depreciation, and Amortization**. \n\nIt's a measure of a company's operating profitability.  Essentially, it tells you how much profit a company makes from its core business operations *before* taking into account factors like financing costs (interest), tax obligations, and non-cash expenses (depreciation and amortization).\n\n\n**Why is EBITDA important?**\n\n* **Comparing companies:** It allows for a more apples-to-apples comparison of profitability between companies in different industries or with different capital structures. \n* **Understanding core performance:**  It focuses on the operating efficiency and revenue generation of a business, independent of its financing choices and accounting treatments.\n* **Valuation:** Investors and analysts often use EBITDA as a basis for valuing companies, particularly in leveraged buyouts or mergers and acquisitions.\n\n**Keep in mind:** \n\nWhile EBITDA is a useful metric, it shouldn't be used in isolation. It's important to consider other factors like net income, cash flow, and debt levels to get a complete picture of a company's financial health.\n\n\nLet me know if you have any other questions about EBITDA or would like more details!", latency_seconds=11.885605096817017, token_count=248, correctness=1.0),
 InferenceResult(generated_answer='The sum of angles in a triangle is always **180 degrees**. \n', latency_seconds=0.9250378608703613, token_count=18, correctness=0.5),
 InferenceResult(generated_answer='You can use the `json` module in Python to serialize a dictionary to a JSON string. \n\nHere\'s how:\n\n```python\nimport json\n\nmy_dict = {"name": "John Doe", "age": 30, "city": "New York"}\n\n# Serialize the dictionary to a JSON string\njson_string = json.dumps(my_dict)\n\nprint(json_string)\n```\n\n**Explanation:**\n\n1. **`import json`:** Imports the `json` module, which provides functions for working with JSON data.\n2. **`my_dict = {"name": "John Doe", "age": 30, "city": "New York"}`:** Creates a sample dictionary.\n3. **`json_string = json.dumps(my_dict)`:**  Uses the `json.dumps()` function to serialize the dictionary (`my_dict`) into a JSON-formatted string and store it in the `json_string` variable.\n\n**Output:**\n\n```json\n{"name": "John Doe", "age": 30, "city": "New York"}\n```\n\n\n\nLet me know if you\'d like to see how to do the opposite (deserialize a JSON string back into a Python dictionary)!', latency_seconds=12.556668043136597, token_count=268, correctness=0.9),
 InferenceResult(generated_answer="Loss Adjustment Expense (LAE) refers to the **costs incurred by an insurance company in processing and settling claims**.  \n\n**Here's a breakdown:**\n\n* **What it includes:** LAE covers various expenses related to handling a claim, such as:\n    * **Salaries and benefits for adjusters and other staff** who investigate and evaluate claims.\n    * **Travel and accommodation expenses** for adjusters visiting claim sites.\n    * **Legal fees and court costs** if a claim goes to litigation.\n    * **Administrative costs** like document processing, communication with claimants, and claim management software.\n    * **Repairs or replacement costs** covered by the insurance policy (although these are sometimes categorized separately).\n\n* **Impact on profitability:** LAE can significantly impact an insurance company's profitability. \n    * High LAEs indicate that the company is spending more to settle claims than it's receiving in premiums, leading to potential losses.  \n    * Effective claim management and cost control strategies are crucial for minimizing LAEs and improving profitability.\n\n* **Financial reporting:** LAE is recorded as an expense on an insurance company's income statement. It is often categorized separately from incurred claims (the total amount paid out for claims) and loss ratios (LAE plus incurred claims as a percentage of premiums earned).\n\n\nUnderstanding LAE is essential for:\n\n* **Insurance companies:** To manage their expenses, price policies accurately, and ensure profitability.\n* **Policyholders:** To understand the potential costs associated with filing a claim and to choose insurance providers with efficient claim processing practices.", latency_seconds=15.13747787475586, token_count=330, correctness=0.9),
 InferenceResult(generated_answer='```python\nwords = ["hello", "world", "python"]\n\nword_lengths = {word: len(word) for word in words}\n\nprint(word_lengths) \n```\n\n**Explanation:**\n\n* **`{word: len(word) for word in words}`**: This is the dictionary comprehension. \n    *  **`for word in words`**: This iterates through each `word` in the `words` list.\n    * **`word: len(word)`**: For each `word`, it creates a key-value pair where the key is the `word` itself and the value is the length of the `word` calculated using `len(word)`.\n\nLet me know if you have any other Python questions!', latency_seconds=7.894730091094971, token_count=161, correctness=0.9),
 InferenceResult(generated_answer='In finance, **beta (β)** measures a stock\'s volatility in relation to the overall market.  \n\n**Here\'s a breakdown:**\n\n* **Volatility:** How much a stock\'s price fluctuates up and down. A high beta means large price swings, while a low beta means smaller swings.\n* **Market:** Usually represented by a benchmark index like the S&P 500, which tracks the performance of a broad segment of the market.\n\n**Beta tells you:**\n\n* For every 1% change in the market (benchmark), how much does the stock\'s price tend to change?\n\n**Example:**\n\nA beta of 1.2 means that for every 1% increase in the market, the stock is expected to increase by 1.2%. Conversely, if the market drops 2%, the stock would likely drop by 2.4%.\n\n* **Beta = 1:** The stock moves in line with the market.\n* **Beta > 1:** The stock is more volatile than the market (considered "riskier").\n* **Beta < 1:** The stock is less volatile than the market (considered "safer").\n\n**Important considerations:**\n\n* Beta is a historical measure and doesn\'t predict future performance.\n* Different investors have different risk tolerances. A high beta stock might be attractive to some investors seeking higher returns, while others prefer lower-beta stocks for stability.\n* Beta is just one factor to consider when making investment decisions. Other factors include company fundamentals, industry trends, and overall market conditions.\n\n\nLet me know if you have any other questions!', latency_seconds=16.3372859954834, token_count=340, correctness=0.8),
 InferenceResult(generated_answer='```python\nimport time\n\nclass Timer:\n    def __init__(self):\n        self.start_time = None\n\n    def __enter__(self):\n        self.start_time = time.perf_counter()  # Use perf_counter for high precision timing\n        return self\n\n    def __exit__(self, exc_type, exc_value, traceback):\n        end_time = time.perf_counter()\n        elapsed_time = end_time - self.start_time\n        print(f"Elapsed time: {elapsed_time:.4f} seconds") \n\n# Example usage\nwith Timer() as timer:\n    # Code to be timed goes here\n    time.sleep(1)  # Simulate some work\n\n\n```\n\n**Explanation:**\n\n1. **`Timer` Class:**\n   - `__init__(self)`: Initializes the `start_time` attribute to `None`.\n2. **Context Manager Methods:**\n   - `__enter__(self)`: Called when entering the `with` statement. \n     - Records the current time using `time.perf_counter()`, which provides high-resolution timestamps.\n     - Returns `self` (the `Timer` object) to allow access within the `with` block if needed.\n   - `__exit__(self, exc_type, exc_value, traceback)`: Called when exiting the `with` statement, regardless of exceptions.\n     - Calculates the elapsed time by subtracting `start_time` from the current time (`time.perf_counter()`).\n     - Prints the elapsed time formatted to four decimal places.\n\n3. **Example Usage:**\n   - The `with Timer() as timer:` block creates a `Timer` object and enters the context manager.\n   - Inside the `with` block, you place the code you want to time. Here, `time.sleep(1)` simulates some work taking one second.\n   - When the `with` block ends, the `__exit__` method of the `Timer` object is called automatically, printing the elapsed time.\n\n\n\nLet me know if you\'d like any modifications or have more questions!', latency_seconds=21.83666205406189, token_count=464, correctness=0.8),
 InferenceResult(generated_answer='In claim settlement, a "release" is a legal document that **completely discharges or absolves a party from any further liability** related to a particular claim. \n\nHere\'s a breakdown:\n\n* **Who signs it:**  Typically, both the claimant (the person making the claim) and the defendant (the person being sued or held responsible) sign a release.\n* **What it does:** It legally states that the claimant agrees to drop all claims against the defendant related to the specific incident or situation outlined in the document. \n\n* **Why it\'s used:** Releases are often used in personal injury cases, property damage claims, and other situations where a settlement agreement has been reached. They provide finality to the dispute and protect both parties from future legal action stemming from the same issue.\n* **Important considerations:**\n\n    * **Full disclosure:** Both parties need to fully understand all aspects of the claim and the terms of the release before signing. \n    * **Legal advice:** It\'s crucial for each party to consult with an attorney to ensure they understand their rights and obligations before signing a release.\n    * **Irrevocability:** Once signed, releases are generally binding and difficult to overturn.\n\n\nEssentially, a release acts as a legal "full stop" on a claim, preventing any further legal action related to the settled matter. \n', latency_seconds=13.944689989089966, token_count=282, correctness=0.9),
 InferenceResult(generated_answer='Market capitalization, often shortened to "market cap," is the total value of a publicly traded company\'s outstanding shares.  \n\n**Here\'s how it\'s calculated:**\n\n* **Multiply the current share price by the total number of outstanding shares.**\n\n   *Formula:* Market Cap = Share Price x Number of Outstanding Shares\n\n**What does market cap tell us?**\n\nMarket cap is a widely used measure of a company\'s size and value. \n\n* **Larger market caps generally indicate:**\n    * More established companies\n    * Higher trading volume\n    * Greater financial stability (but not always!)\n\n* **Smaller market caps can represent:**\n    * Companies with high growth potential\n    * More risk involved due to their size and less proven track record\n\n**Market cap classifications:**\n\nCompanies are often categorized by their market cap:\n\n* **Large-cap:** Typically companies with a market cap of $10 billion or more.\n* **Mid-cap:** Companies with a market cap between $2 billion and $10 billion.\n* **Small-cap:** Companies with a market cap below $2 billion.\n\n**Important notes:**\n\n* Market cap can fluctuate daily based on changes in share price.\n* It\'s not the only factor to consider when evaluating a company\'s value. Other factors like profitability, debt levels, and industry outlook also matter.\n\n\nLet me know if you have any other questions!', latency_seconds=13.985253810882568, token_count=299, correctness=0.9),
 InferenceResult(generated_answer='"Loss of use" coverage is an insurance term that refers to the additional expense you incur when your covered property is damaged and unusable.  \n\n**Here\'s a breakdown:**\n\n* **Scenario:** Imagine your car gets totaled in an accident. You can\'t drive it anymore, so you need to rent another vehicle to get around while yours is being repaired or replaced.\n* **Loss of use coverage kicks in:** This type of coverage would help pay for the cost of renting a temporary vehicle during this time.\n\n**Key points about loss of use coverage:**\n\n* **It\'s often included with other policies:**  You might find it as part of your auto, homeowners, or renters insurance policy.\n* **Not always automatic:** Sometimes, you need to specifically purchase "loss of use" coverage, so check your policy details.\n* **Coverage limits:** Policies have maximum amounts they\'ll pay for loss of use expenses.\n* **Duration of coverage:** The length of time your policy covers rental costs varies by policy.\n\n**Examples of situations where loss of use might apply:**\n\n* **Car accident:** Renting a car while yours is repaired.\n* **Home fire:** Staying in a hotel while your home is uninhabitable.\n* **Damaged appliance:** Paying for temporary cleaning or refrigeration services.\n\n\n**If you\'re unsure about your coverage, always contact your insurance provider directly.**', latency_seconds=13.00085711479187, token_count=290, correctness=0.9),

In [10]:
result_dataset.inferences["mistral"][0]

InferenceResult(generated_answer=' In finance, a hedge refers to an investment or trading strategy that is intended to offset potential losses in another investment. The goal of hedging is to reduce the risk of adverse price movements in an asset, portfolio, or position.\n\nHedging strategies can be used for various purposes such as:\n\n1. Protecting against fluctuations in exchange rates (currency hedging)\n2. Guarding against changes in interest rates (interest rate hedging)\n3. Mitigating risks associated with commodity prices (commodity hedging)\n4. Reducing volatility due to market uncertainty or unforeseen events (risk management)\n\nFor example, an airline may enter into a currency hedge agreement to protect against fluctuations in the exchange rate between their local currency and the currencies they purchase fuel from. This helps them maintain a steady cost for their operations even if the exchange rate changes significantly during the contract period.', latency_seconds=7.682900905609131, token_count=199, correctness=0.9)

In [11]:
result_dataset.inferences["mistral"][1]

InferenceResult(generated_answer=" In the context of insurance, underwriting refers to the process by which an insurance company evaluates the acceptance of an applicant and determines appropriate coverage, premiums, and risks for a particular insurance policy. The underwriting process involves assessing various factors such as the insured's age, health status, lifestyle, occupation, and other relevant details to evaluate the risk profile of the potential client. Based on this assessment, the insurance company will decide whether to issue the policy, decline it, or offer coverage with different terms and conditions, including premiums. The goal of underwriting is to ensure that the insurance company can accurately price and manage the risks associated with the policies they issue.", latency_seconds=5.2038798332214355, token_count=139, correctness=1.0)

In [12]:
models_preds = {
    "mistral": {
        "generated_answer": [],
        "latency_seconds": [],
        "token_count": [],
        "correctness": [],
    },
    "gemma2": {
        "generated_answer": [],
        "latency_seconds": [],
        "token_count": [],
        "correctness": [],
    },
}

for model in models:
    model_inference_results = result_dataset.inferences[model]
    for model_inference_result in model_inference_results:
        models_preds[model]["generated_answer"].append(model_inference_result.generated_answer)
        models_preds[model]["latency_seconds"].append(model_inference_result.latency_seconds)
        models_preds[model]["token_count"].append(model_inference_result.token_count)
        models_preds[model]["correctness"].append(model_inference_result.correctness)

In [47]:
models_preds_df = pd.DataFrame(models_preds)
mistral_preds_df = pd.DataFrame(models_preds["mistral"])
gemma_preds_df = pd.DataFrame(models_preds["gemma2"])

In [52]:
mistral_preds_df["correctness_over_latency"] = mistral_preds_df["correctness"] / mistral_preds_df["latency_seconds"]
gemma_preds_df["correctness_over_latency"] = gemma_preds_df["correctness"] / gemma_preds_df["latency_seconds"]

In [53]:
models_preds_df

,mistral,gemma2
generated_answer,"[ In finance, a hedge refers to an investment ...",[A hedge can have a few different meanings dep...
latency_seconds,"[7.682900905609131, 5.2038798332214355, 3.6114...","[13.747304201126099, 10.330981731414795, 1.835..."
token_count,"[199, 139, 96, 333, 317, 128, 178, 130, 143, 2...","[300, 222, 38, 380, 248, 18, 268, 330, 161, 34..."
correctness,"[0.9, 1.0, 1.0, 0.8, 0.9, 0.5, 0.75, 0.9, 0.9,...","[0.7, 0.9, 1.0, 0.8, 1.0, 0.5, 0.9, 0.9, 0.9, ..."

In [54]:
mistral_preds_df

,generated_answer,latency_seconds,token_count,correctness,correctness_over_latency
0,"In finance, a hedge refers to an investment o...",7.682901,199,0.9,0.117143
1,"In the context of insurance, underwriting ref...",5.203880,139,1.0,0.192164
2,Factorial of a number is the product of all p...,3.611438,96,1.0,0.276898
3,"Yes, an insurance company can potentially can...",12.971416,333,0.8,0.061674
4,"EBITDA stands for Earnings Before Interest, T...",11.995500,317,0.9,0.075028
...,...,...,...,...,...
296,"Tail coverage, in the context of software tes...",6.524011,161,0.0,0.000000
297,An insurance agent acts as a representative o...,9.965055,263,0.8,0.080281
298,It's important to notify your insurance compa...,5.140765,121,0.9,0.175071
299,A Python decorator is a special type of funct...,10.079153,264,0.9,0.089293
300,The SQL `HAVING` clause is used in aggregate ...,8.004983,191,0.9,0.112430

In [55]:
gemma_preds_df

,generated_answer,latency_seconds,token_count,correctness,correctness_over_latency
0,A hedge can have a few different meanings depe...,13.747304,300,0.7,0.050919
1,Underwriting in insurance is the process of **...,10.330982,222,0.9,0.087117
2,7! (7 factorial) is:\n\n7 * 6 * 5 * 4 * 3 * 2 ...,1.835027,38,1.0,0.544951
3,It depends on your specific insurance policy a...,17.416100,380,0.8,0.045935
4,"EBITDA stands for **Earnings Before Interest, ...",11.885605,248,1.0,0.084135
...,...,...,...,...,...
296,"""Tail coverage"" in the context of software tes...",9.377324,358,0.0,0.000000
297,An insurance agent acts as a **mediator** betw...,11.280446,432,0.7,0.062054
298,It's best to notify your insurance company **a...,5.556152,210,0.8,0.143985
299,A Python decorator is a powerful tool that all...,13.802711,529,0.8,0.057960
300,The `HAVING` clause in SQL is used to filter t...,10.633370,407,0.9,0.084639

In [56]:
models_preds_df.to_csv("data/predictions/models_preds.csv", index=False)
mistral_preds_df.to_csv("data/predictions/mistral_preds.csv", index=False)
gemma_preds_df.to_csv("data/predictions/gemma_preds.csv", index=False)

In [57]:
mistral_preds_df[["latency_seconds", "token_count", "correctness", "correctness_over_latency"]].describe()

       latency_seconds  token_count  correctness  correctness_over_latency
count       301.000000   301.000000   301.000000                301.000000
mean          8.380791   213.435216     0.822625                  0.153047
std           4.459801   114.327104     0.203626                  0.180286
min           0.406551     8.000000     0.000000                  0.000000
25%           5.154355   130.000000     0.800000                  0.071788
50%           7.958181   199.000000     0.900000                  0.104182
75%          10.677596   280.000000     0.900000                  0.170830
max          23.853597   600.000000     1.000000                  2.213744

In [58]:
gemma_preds_df[["latency_seconds", "token_count", "correctness", "correctness_over_latency"]].describe()

       latency_seconds  token_count  correctness  correctness_over_latency
count       301.000000   301.000000   301.000000                301.000000
mean         11.321711   286.059801     0.846811                  0.184471
std           6.617986   148.124395     0.152606                  0.308482
min           0.421489    10.000000     0.000000                  0.000000
25%           6.526933   172.000000     0.800000                  0.051139
50%          10.627947   320.000000     0.900000                  0.078031
75%          16.117235   388.000000     0.900000                  0.132624
max          28.429469   625.000000     1.000000                  2.135288

In [59]:
mistral_preds_df.columns = [col + "_mistral" for col in mistral_preds_df.columns]
gemma_preds_df.columns = [col + "_gemma" for col in gemma_preds_df.columns]

all_preds_df = pd.concat([mistral_preds_df, gemma_preds_df], axis=1)

all_preds_df

,generated_answer_mistral,latency_seconds_mistral,token_count_mistral,correctness_mistral,correctness_over_latency_mistral,generated_answer_gemma,latency_seconds_gemma,token_count_gemma,correctness_gemma,correctness_over_latency_gemma
0,"In finance, a hedge refers to an investment o...",7.682901,199,0.9,0.117143,A hedge can have a few different meanings depe...,13.747304,300,0.7,0.050919
1,"In the context of insurance, underwriting ref...",5.203880,139,1.0,0.192164,Underwriting in insurance is the process of **...,10.330982,222,0.9,0.087117
2,Factorial of a number is the product of all p...,3.611438,96,1.0,0.276898,7! (7 factorial) is:\n\n7 * 6 * 5 * 4 * 3 * 2 ...,1.835027,38,1.0,0.544951
3,"Yes, an insurance company can potentially can...",12.971416,333,0.8,0.061674,It depends on your specific insurance policy a...,17.416100,380,0.8,0.045935
4,"EBITDA stands for Earnings Before Interest, T...",11.995500,317,0.9,0.075028,"EBITDA stands for **Earnings Before Interest, ...",11.885605,248,1.0,0.084135
...,...,...,...,...,...,...,...,...,...,...
296,"Tail coverage, in the context of software tes...",6.524011,161,0.0,0.000000,"""Tail coverage"" in the context of software tes...",9.377324,358,0.0,0.000000
297,An insurance agent acts as a representative o...,9.965055,263,0.8,0.080281,An insurance agent acts as a **mediator** betw...,11.280446,432,0.7,0.062054
298,It's important to notify your insurance compa...,5.140765,121,0.9,0.175071,It's best to notify your insurance company **a...,5.556152,210,0.8,0.143985
299,A Python decorator is a special type of funct...,10.079153,264,0.9,0.089293,A Python decorator is a powerful tool that all...,13.802711,529,0.8,0.057960
300,The SQL `HAVING` clause is used in aggregate ...,8.004983,191,0.9,0.112430,The `HAVING` clause in SQL is used to filter t...,10.633370,407,0.9,0.084639

In [60]:
all_preds_df.loc[(all_preds_df["correctness_mistral"] > all_preds_df["correctness_gemma"])]

,generated_answer_mistral,latency_seconds_mistral,token_count_mistral,correctness_mistral,correctness_over_latency_mistral,generated_answer_gemma,latency_seconds_gemma,token_count_gemma,correctness_gemma,correctness_over_latency_gemma
0,"In finance, a hedge refers to an investment o...",7.682901,199,0.90,0.117143,A hedge can have a few different meanings depe...,13.747304,300,0.7,0.050919
1,"In the context of insurance, underwriting ref...",5.203880,139,1.00,0.192164,Underwriting in insurance is the process of **...,10.330982,222,0.9,0.087117
9,"In finance, Beta (β) is a measure of the risk...",9.996770,253,0.95,0.095031,"In finance, **beta (β)** measures a stock's vo...",16.337286,340,0.8,0.048968
16,To write a SQL query that counts the number o...,7.557624,174,0.80,0.105853,"```sql\nSELECT country, COUNT(*) AS customer_c...",7.441372,148,0.5,0.067192
30,Catastrophe (CAT) claims and regular insuranc...,19.212674,477,0.90,0.046844,Catastrophe (CAT) claims are distinct from reg...,18.971318,414,0.7,0.036898
...,...,...,...,...,...,...,...,...,...,...
280,A 'Claims-Made' policy is a type of insurance...,9.906242,249,1.00,0.100946,A **claims-made insurance policy** provides co...,9.395107,359,0.9,0.095795
294,"In Python, both `is` and `==` are used for co...",12.536989,317,0.90,0.071788,"In Python, both `is` and `==` are used for com...",9.071377,346,0.8,0.088189
297,An insurance agent acts as a representative o...,9.965055,263,0.80,0.080281,An insurance agent acts as a **mediator** betw...,11.280446,432,0.7,0.062054
298,It's important to notify your insurance compa...,5.140765,121,0.90,0.175071,It's best to notify your insurance company **a...,5.556152,210,0.8,0.143985
299,A Python decorator is a special type of funct...,10.079153,264,0.90,0.089293,A Python decorator is a powerful tool that all...,13.802711,529,0.8,0.057960

In [61]:
all_preds_df.loc[(all_preds_df["correctness_mistral"] < all_preds_df["correctness_gemma"])]

,generated_answer_mistral,latency_seconds_mistral,token_count_mistral,correctness_mistral,correctness_over_latency_mistral,generated_answer_gemma,latency_seconds_gemma,token_count_gemma,correctness_gemma,correctness_over_latency_gemma
4,"EBITDA stands for Earnings Before Interest, T...",11.995500,317,0.90,0.075028,"EBITDA stands for **Earnings Before Interest, ...",11.885605,248,1.0,0.084135
6,"In Python, you can convert a dictionary to a ...",7.172343,178,0.75,0.104568,You can use the `json` module in Python to ser...,12.556668,268,0.9,0.071675
10,Here's a simple Python context manager that t...,9.043648,226,0.20,0.022115,```python\nimport time\n\nclass Timer:\n de...,21.836662,464,0.8,0.036636
14,A depreciation holdback refers to a portion o...,8.154342,217,0.40,0.049054,A **depreciation holdback** is a provision in ...,18.899816,387,0.5,0.026455
15,The smallest unit of life that can independen...,5.088704,132,0.80,0.157211,The smallest unit of life is the **cell**. \n\...,5.339798,117,0.9,0.168546
...,...,...,...,...,...,...,...,...,...,...
286,The combined ratio is a measure used in the i...,8.088777,229,0.90,0.111265,The **Combined Ratio** is a key metric in insu...,8.744785,334,1.0,0.114354
288,"To add type hints to a Python function, you c...",14.654999,368,0.00,0.000000,Type hints in Python are annotations that spec...,9.759008,373,0.7,0.071729
289,To find all `.log` files modified within the ...,8.210119,216,0.80,0.097441,"```bash\nfind /var/log -type f -name ""*.log"" -...",4.574854,172,1.0,0.218586
292,You can count the number of lines in a file u...,6.525663,153,0.80,0.122593,```bash\nwc -l <filename> \n```\n\n**Explanati...,2.808803,103,0.9,0.320421
293,The boiling point of water at standard atmosp...,2.545785,65,0.90,0.353526,The boiling point of water at sea level is **1...,0.654164,19,1.0,1.528669

In [62]:
all_preds_df.loc[(all_preds_df["latency_seconds_mistral"] > all_preds_df["latency_seconds_gemma"])]

,generated_answer_mistral,latency_seconds_mistral,token_count_mistral,correctness_mistral,correctness_over_latency_mistral,generated_answer_gemma,latency_seconds_gemma,token_count_gemma,correctness_gemma,correctness_over_latency_gemma
2,Factorial of a number is the product of all p...,3.611438,96,1.0,0.276898,7! (7 factorial) is:\n\n7 * 6 * 5 * 4 * 3 * 2 ...,1.835027,38,1.0,0.544951
4,"EBITDA stands for Earnings Before Interest, T...",11.995500,317,0.9,0.075028,"EBITDA stands for **Earnings Before Interest, ...",11.885605,248,1.0,0.084135
5,The sum of angles in a triangle always adds u...,4.837385,128,0.5,0.103362,The sum of angles in a triangle is always **18...,0.925038,18,0.5,0.540518
16,To write a SQL query that counts the number o...,7.557624,174,0.8,0.105853,"```sql\nSELECT country, COUNT(*) AS customer_c...",7.441372,148,0.5,0.067192
18,"As of now, Mandarin Chinese is considered to ...",3.156082,80,0.9,0.285164,The language with the most native speakers is ...,1.790426,35,1.0,0.558526
...,...,...,...,...,...,...,...,...,...,...
289,To find all `.log` files modified within the ...,8.210119,216,0.8,0.097441,"```bash\nfind /var/log -type f -name ""*.log"" -...",4.574854,172,1.0,0.218586
290,The HTTP status code 401 indicates that the r...,4.993762,133,0.8,0.160200,HTTP status code **401 Unauthorized** means th...,2.987311,110,0.8,0.267799
292,You can count the number of lines in a file u...,6.525663,153,0.8,0.122593,```bash\nwc -l <filename> \n```\n\n**Explanati...,2.808803,103,0.9,0.320421
293,The boiling point of water at standard atmosp...,2.545785,65,0.9,0.353526,The boiling point of water at sea level is **1...,0.654164,19,1.0,1.528669
294,"In Python, both `is` and `==` are used for co...",12.536989,317,0.9,0.071788,"In Python, both `is` and `==` are used for com...",9.071377,346,0.8,0.088189

In [63]:
all_preds_df.loc[(all_preds_df["latency_seconds_mistral"] < all_preds_df["latency_seconds_gemma"])]

,generated_answer_mistral,latency_seconds_mistral,token_count_mistral,correctness_mistral,correctness_over_latency_mistral,generated_answer_gemma,latency_seconds_gemma,token_count_gemma,correctness_gemma,correctness_over_latency_gemma
0,"In finance, a hedge refers to an investment o...",7.682901,199,0.90,0.117143,A hedge can have a few different meanings depe...,13.747304,300,0.7,0.050919
1,"In the context of insurance, underwriting ref...",5.203880,139,1.00,0.192164,Underwriting in insurance is the process of **...,10.330982,222,0.9,0.087117
3,"Yes, an insurance company can potentially can...",12.971416,333,0.80,0.061674,It depends on your specific insurance policy a...,17.416100,380,0.8,0.045935
6,"In Python, you can convert a dictionary to a ...",7.172343,178,0.75,0.104568,You can use the `json` module in Python to ser...,12.556668,268,0.9,0.071675
7,"""Loss Adjustment Expense"" (LAE) refers to the...",5.023799,130,0.90,0.179147,Loss Adjustment Expense (LAE) refers to the **...,15.137478,330,0.9,0.059455
...,...,...,...,...,...,...,...,...,...,...
296,"Tail coverage, in the context of software tes...",6.524011,161,0.00,0.000000,"""Tail coverage"" in the context of software tes...",9.377324,358,0.0,0.000000
297,An insurance agent acts as a representative o...,9.965055,263,0.80,0.080281,An insurance agent acts as a **mediator** betw...,11.280446,432,0.7,0.062054
298,It's important to notify your insurance compa...,5.140765,121,0.90,0.175071,It's best to notify your insurance company **a...,5.556152,210,0.8,0.143985
299,A Python decorator is a special type of funct...,10.079153,264,0.90,0.089293,A Python decorator is a powerful tool that all...,13.802711,529,0.8,0.057960
300,The SQL `HAVING` clause is used in aggregate ...,8.004983,191,0.90,0.112430,The `HAVING` clause in SQL is used to filter t...,10.633370,407,0.9,0.084639

In [65]:
all_preds_df.loc[(all_preds_df["correctness_over_latency_mistral"] > all_preds_df["correctness_over_latency_gemma"])]

,generated_answer_mistral,latency_seconds_mistral,token_count_mistral,correctness_mistral,correctness_over_latency_mistral,generated_answer_gemma,latency_seconds_gemma,token_count_gemma,correctness_gemma,correctness_over_latency_gemma
0,"In finance, a hedge refers to an investment o...",7.682901,199,0.90,0.117143,A hedge can have a few different meanings depe...,13.747304,300,0.7,0.050919
1,"In the context of insurance, underwriting ref...",5.203880,139,1.00,0.192164,Underwriting in insurance is the process of **...,10.330982,222,0.9,0.087117
3,"Yes, an insurance company can potentially can...",12.971416,333,0.80,0.061674,It depends on your specific insurance policy a...,17.416100,380,0.8,0.045935
6,"In Python, you can convert a dictionary to a ...",7.172343,178,0.75,0.104568,You can use the `json` module in Python to ser...,12.556668,268,0.9,0.071675
7,"""Loss Adjustment Expense"" (LAE) refers to the...",5.023799,130,0.90,0.179147,Loss Adjustment Expense (LAE) refers to the **...,15.137478,330,0.9,0.059455
...,...,...,...,...,...,...,...,...,...,...
295,"In an insurance policy, the deductible is the...",4.493146,119,0.90,0.200305,A **deductible** in an insurance policy is the...,7.331132,279,0.9,0.122764
297,An insurance agent acts as a representative o...,9.965055,263,0.80,0.080281,An insurance agent acts as a **mediator** betw...,11.280446,432,0.7,0.062054
298,It's important to notify your insurance compa...,5.140765,121,0.90,0.175071,It's best to notify your insurance company **a...,5.556152,210,0.8,0.143985
299,A Python decorator is a special type of funct...,10.079153,264,0.90,0.089293,A Python decorator is a powerful tool that all...,13.802711,529,0.8,0.057960
300,The SQL `HAVING` clause is used in aggregate ...,8.004983,191,0.90,0.112430,The `HAVING` clause in SQL is used to filter t...,10.633370,407,0.9,0.084639

In [66]:
all_preds_df.loc[(all_preds_df["correctness_over_latency_mistral"] < all_preds_df["correctness_over_latency_gemma"])]

,generated_answer_mistral,latency_seconds_mistral,token_count_mistral,correctness_mistral,correctness_over_latency_mistral,generated_answer_gemma,latency_seconds_gemma,token_count_gemma,correctness_gemma,correctness_over_latency_gemma
2,Factorial of a number is the product of all p...,3.611438,96,1.0,0.276898,7! (7 factorial) is:\n\n7 * 6 * 5 * 4 * 3 * 2 ...,1.835027,38,1.0,0.544951
4,"EBITDA stands for Earnings Before Interest, T...",11.995500,317,0.9,0.075028,"EBITDA stands for **Earnings Before Interest, ...",11.885605,248,1.0,0.084135
5,The sum of angles in a triangle always adds u...,4.837385,128,0.5,0.103362,The sum of angles in a triangle is always **18...,0.925038,18,0.5,0.540518
10,Here's a simple Python context manager that t...,9.043648,226,0.2,0.022115,```python\nimport time\n\nclass Timer:\n de...,21.836662,464,0.8,0.036636
15,The smallest unit of life that can independen...,5.088704,132,0.8,0.157211,The smallest unit of life is the **cell**. \n\...,5.339798,117,0.9,0.168546
...,...,...,...,...,...,...,...,...,...,...
289,To find all `.log` files modified within the ...,8.210119,216,0.8,0.097441,"```bash\nfind /var/log -type f -name ""*.log"" -...",4.574854,172,1.0,0.218586
290,The HTTP status code 401 indicates that the r...,4.993762,133,0.8,0.160200,HTTP status code **401 Unauthorized** means th...,2.987311,110,0.8,0.267799
292,You can count the number of lines in a file u...,6.525663,153,0.8,0.122593,```bash\nwc -l <filename> \n```\n\n**Explanati...,2.808803,103,0.9,0.320421
293,The boiling point of water at standard atmosp...,2.545785,65,0.9,0.353526,The boiling point of water at sea level is **1...,0.654164,19,1.0,1.528669
294,"In Python, both `is` and `==` are used for co...",12.536989,317,0.9,0.071788,"In Python, both `is` and `==` are used for com...",9.071377,346,0.8,0.088189

In [71]:
queries = []
expected_answers = []

for sample in dataset.samples:
    queries.append(sample.query)
    expected_answers.append(sample.expected_answer)

all_preds_df["query"] = queries
all_preds_df["expected_answer"] = expected_answers

In [72]:
all_preds_df.to_csv("all_preds_df.csv", index=False)